### ISSUE TITLE
graph.updateItem() does not update node's `linkPoints`'s visible

### ISSUE THREAD

**Issue by fix777** [antvis/G6#1040]
* **G6 Version**: 3.2.4
* **Platform**: macOS Catalina(10.15.1 (19B88))
* **Mini Showcase(like screenshots)**:

initial view:

![image](https://user-images.githubusercontent.com/19484638/70693904-58c59680-1cf9-11ea-8895-72e1395bad6c.png)

clicked view:

![image](https://user-images.githubusercontent.com/19484638/70695769-60873a00-1cfd-11ea-99f6-a70621da8e9c.png)

* **CodePen Link**: https://codesandbox.io/s/hungry-meninsky-8404o

**Comment by Yanyan-Wang** [comment]
We found that it is because `updateItem` only updates the existing shapes on a node or an edge. 

In your case, G6 draws the node with two shapes according to the initial configurations: a blue circle and a link point circle with size 0. `updateItem` did not add new shape: the top link point circle onto the node.

We will try to solve this problem. For now, you can take the alternative temporary solution: 
- set the opacity or size to 0 for all the linkPoints in the data or other initial configurations so that G6 will draw all of them;
- change the opacity or size by `updateItem` to show them in the listener.

Thanks for your report.

**Comment by fix777** [comment]
Got it. Thanks.
