### ISSUE TITLE
Feature Request. Is it possible to convert .dot scripts into G6 graphs?

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/G6#1352]
The DOT language is the default graph description language for [Graphviz](https://www.graphviz.org/).  Writing pure js to define a graph is too time-consuming at the moment. It would be super helpful if there is a way to create a G6 graph using the dot language like Graphviz, like the example [here](https://edotor.net/).

**Comment by Yanyan-Wang** [comment]
Thanks, It will be a good feature.

To address that, we might just need a compiler for converting DOT language to JSON since the input data of G6 is in JSON format. I think it can be an independent plugin. 

But it might not be a near-term target of G6. Maybe there is available tool to do so already. And we welcome PR from communities :)

**Comment by laubonghaudoi** [comment]
Thank you. Conversion from DOT to JSON is actually [supported](https://www.graphviz.org/doc/info/output.html#a:xdot_json) by Graphviz. But the output json is still incompatible with G6's required format, especially the grammar for defining sub-groups. And the grammar for styling also needs a bit of revamp.

But anyways, even without stylizing, merely supporting the conversion of node and edge definitions in DOT language would save a lot of time than writing pure js. Hope this will be supported some day.
