### ISSUE TITLE
Feature request: webgl client rendering

### ISSUE THREAD

**Issue by enodr** [antvis/G6#1383]
Hi,

G6 is a very powerfull lib but when rendering hundreds of nodes and edges the browser quickly struggles.

Adding webgl renderer would be a really great feature.

Linkurious and Keylines support webgl renderer for a long time and really outperforms G6 when rendering lot of nodes.

**Comment by Yanyan-Wang** [comment]
Thanks. 

Actually, we are considering webgl for layout currently.

But I think G6 is able to support hundreds of nodes and edges well without webgl.  We have tested 10 thousand nodes with canvas renderer, G6 performs well. Which renderer are you using? Canvas or SVG?

**Comment by enodr** [comment]
Using default renderer (Canvas?) on G6 version 3.4.4. Performance on a mid range laptop (core i7) is barely acceptable when having 200 nodes. Waiting for webgl for more complex graphs!

**Comment by Yanyan-Wang** [comment]
Then rendering performance is affected by the total number of shapes in the graph and the canvas size.

Do you use custom node where lots of shapes exist in each node item? Or a large canvas like 10,000*10,000 with large elements which can be proportional scaled

**Comment by enodr** [comment]
I have been doing some tests with either custom nodes but also the basic circle node and wih only hundreds of nodes in a small canvas the CPU it going 100% can. Dragging the canvas is already very slow.
Using Chrome profiler I see that most of the CPU time is spent in g6.min.js = "Animation Frame Fired", n.drawChildren, n.draw, n._drawRegion, etc.

Maybe I should open another ticket for this? Maybe a wrong use of some g6 graph behavior or initialisation in my app? Note that using antvis/graphin as an example I have the same problem (adding a graph with 1000 nodes kills the browser).

**Comment by baizn** [comment]
> We have tested 10 thousand nodes with canvas renderer, G6 performs well.

please refer here：https://github.com/antvis/G6/tree/master/stories/Performance

**Comment by anirudhsama** [comment]
What do you mean by that? I'm sending a JSON response of all nodes with positions and the edges. But creating this graph on the frontend is slow.

**Comment by HananoshikaYomaru** [comment]
I think rendering a graph in webGL will eventually be a must as the G6 has increasingly become more popular and hence it is sure that more people will want it to render large graph more quickly. I think whether it is rendering on server or client doesn't matter because the bottleneck will be on graph rendering but not graph data calculation. Also sending the graph data between client and server could introduce network latency which will be an unwanted bottleneck for interactive graphs. Sound like using WebGL is the most suitable option.

**Comment by apitts** [comment]
Confirming that I'm encountering performance issues with medium to large graphs as well. The issue is where there is a need to call graph.render() other than initially, i.e. on an interaction. This can easily take >2 seconds for a medium sized network which feels very slow to the user. 

For example, on my computer, graph.render() in this example (https://g6.antv.vision/en/examples/performance/perf#moreData) takes >5 seconds. WebGL would likely be a big improvement on this.....and I think it's more about re-rendering the whole network than it is about the layout which is not overly hard to do server side or to pre-compute.

**Comment by davidpryor** [comment]
Any update if webgl support for graph rendering will be added?

**Comment by Gykonik** [comment]
I would also be very interested in an update regarding webGL support. I'm currently trying to render 5k nodes with approx. 50k edges, and at the moment it is not usable at all, because it is super slow.
