### ISSUE TITLE
how can I render many node smoothly?

### ISSUE THREAD

**Issue by quanghuynguyen1902** [antvis/G6#1507]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

my graph has 150 node and custom configuration. When rendering it is slow and lag. how can I render many node smoothly

**Comment by Yanyan-Wang** [comment]
Which version of G6 are you using?

**Comment by Yanyan-Wang** [comment]
And are you using SVG renderer?

**Comment by quanghuynguyen1902** [comment]
version is 3.4.5 and my code: https://codesandbox.io/s/graph-network-3844q

**Comment by Yanyan-Wang** [comment]
I found there are 585 nodes and 739 edges in your graph, and it looks lag only during the layout process. It is because the force layout calculates the node positions iteratively and the graph will be re-rendered after each iteration. In each iteration, the force layout takes O(n^2) and the number of the iterations is 300 by default. It is the characteristic of the force directed layout algorithm itself. We are planing to implement the layouts with WebGL and GPGPU this year to improve this problem. But the feedback speed of the interactions is fast enough, I think.
