### ISSUE TITLE
Bug: Edge type "arc" fails when combined with `endArrow: true` and `fitView: true`

### ISSUE THREAD

**Issue by raray** [antvis/G6#1546]
**G6 Version**: 3.4.9

**Platform**: Mac Chrome

**CodeSandbox Link**: https://codesandbox.io/s/confident-euler-sgvwb?file=/index.js

**Steps to reproduce:**
1. Create a graph with `fitView: true`
2. Create an edge with type `'arc'` and style `endArrow: true`

**Expected Result**:
A curved edge is rendered with an arrow on the endpoint.

**Actual Result**:
The entire map fails to render with no error message.

**Comment by Yanyan-Wang** [comment]
Thanks. We found there are lots problems about 'arc' after we upgrade the rendering engine of G6. Use 'quadratic' instead pls.

https://g6.antv.vision/en/docs/manual/middle/elements/edges/quadratic/

**Comment by Yanyan-Wang** [comment]
Dear user, sorry to say that we may not fix the 'A' path problem in SVG renderer in current versions (G6 3.x - 4.x) since it is caused by the old rendering engine which we unable to maintain any more. The rendering engine is being upgraded right now, the problems about SVG will be solved by new version in few months. And G6 will be upgraded to 5.x with new rendering engine next year.
