### ISSUE TITLE
Grid plugin does not work as described in manual

### ISSUE THREAD

**Issue by michaelalemu** [antvis/G6#1589]
- **G6 Version**: 3.4.10
- **CodePen Link**: https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

Hello,

in the manual it is shown that the grid is draggable when the user drags the canvas. Unfortunately, this does not work in the example which is provided at the end of the same manual page.

https://g6.antv.vision/en/docs/manual/tutorial/plugins#grid

**Current effect**
Grid does not move when canvas is dragged. But it does respond to zooming. See CodePen for reference.

**Expected effected**
The grid should move along with the canvas when it is dragged as shown here.

![A_y8u6Rrc78uIAAAAAAAAAAABkARQnAQ](https://user-images.githubusercontent.com/6313162/82507434-844b7900-9b02-11ea-9d5d-790979413cee.gif)

**Comment by Yanyan-Wang** [comment]
Yes, it is designed to be fixed after version v3.3. 

That is because the built-in grid is a div with background-image, and if it is allowed to be moved while dragging the canvas, there will be a blank area on the edges of the canvas. As shown in the demo below:
https://codepen.io/Yanyan-Wang/pen/qBdZgLO

If you have any good idea to improve the grid, we will appreciate your PRs.
