### ISSUE TITLE
custom node's key-shape be influenced by global `defaultNode`

### ISSUE THREAD

**Issue by wqcstrong** [antvis/G6#1647]
- **G6 Version**: 3.5.0
- **Platform**: MacOS Catalina 10.15.4
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: [codepen link](https://codepen.io/WQC/pen/NWxGxqP?editors=1010)

**Comment by wqcstrong** [comment]
I just excepted the right anchor point display when be in the ` hover | select ` state, but the key-shape stroke got red because of the global `defaultState` settings which was unexcepted.

**Comment by Yanyan-Wang** [comment]
For the built-in nodes, we stipulate that the priorities of `options` in custom node, `defaultNode` on graph, and `style` in data as:

**options < defaultNode < data**

When user customizing a node with rewritten `draw` function,  we suggest she/he follow the priority rule, e.g. by calling `style = Object.assign(this.options.style, cfg.style);`.

Your program behaves abnormally since you use `options.style` instead of merging the `cfg.style` into it, which will break the priority rules. But the `update` function in the extended node type 'single-node' still follows the rules above, which will be called after the node's state is changed.

Indeed, It is hard for user to understand and it is also not easy to be explained in docs. We will improve the docs as clear as possible later.

**Comment by wqcstrong** [comment]
@Yanyan-Wang Thx~

**Comment by wqcstrong** [comment]
> For the built-in nodes, we stipulate that the priorities of the styles in `options` of custom node, `defaultNode` on graph, and `style` in data as:
> 
> **options < defaultNode < data**
> 
> When user customizing a node with rewritten `draw` function, we suggest she/he follow the priority rule, e.g. by calling `style = Object.assign(this.options.style, cfg.style);`.
> 
> Your program behaves abnormally since you use `options.style` instead of merging the `cfg.style` into it, which will break the priority rules. But the `update` function in the extended node type 'single-node' still follows the rules above, which will be called after the node's state is changed.
> 
> Indeed, It is hard for user to understand and it is also not easy to be explained in docs. We will improve the docs as clear as possible later.

Even if I merged the styles in `draw` function, it still had same problem when hover node.
```js
const style = {
    ...cfg.style,
    ...this.options.style
}
const keyShape = group.addShape("rect", {
    attrs: {
        x: 0,
        y: 0,
        width,
        height,
        ...style
    },
    name: "rect-key-shape",
    draggable: true
});
```

Did that mean I have to rewrite `update` function and re-merge style? 😭
