### ISSUE TITLE
Animating Dagre Graph edges with controlpoints enabled creates animation side-effect.

### ISSUE THREAD

**Issue by selenecodes** [antvis/G6#2181]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://observablehq.com/@selenecodes/combo-minimal-reproduction-case](https://observablehq.com/@selenecodes/combo-minimal-reproduction-case)

### Steps to reproduce
- Load the reproduction
- Look at straight edges and witness the animation slowing down in the middle of an edge (on the control point)

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | Ubuntu 18.04 |
| Browser | 86.0.4240.75 (Official Build) (64-bit) |

**Comment by Yanyan-Wang** [comment]
Hi, selenecodes. This problem is due to the path of the 'straight' polyline edge: `[['M', x1, y1], ['L', (x1 + x2) / 2, (y1 + y2) / 2], ['L', x2, y2]]` with a controlPoint at the midpoint point ((x1 + x2) / 2, (y1 + y2) / 2). There are two segments, the animation will stop at each end of the segments. Use 'line' type edge for 'straight polyline edge' instead to avoid this problem pls.

**Comment by selenecodes** [comment]
Ah I thought as much, I'll see if it's possible to detect straight lines and automatically swap them to a "line" type then. Thanks for the confirmation.
