### ISSUE TITLE
Force layout cannot be centered

### ISSUE THREAD

**Issue by ketys-from-meiro** [antvis/G6#2358]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-sunset-xqhq6?file=/src/index.js)

### Steps to reproduce
See the result in reproduction demo, the nodes on the right side is moved out of canvas area. I was trying to fix it with `fitView` or `fitCenter` properties, but none seems working for `force` layout as I got blank canvas then.

| Environment | Info |
|---|---|
| g6 | 4.0.0 |
| System | OSX Mojave |
| Browser | Chrome 87.0.4280.67 |

**Comment by Yanyan-Wang** [comment]
Since the force layout is iteratively updated and the items on the canvas are kept moving during the process, and the `fitView` takes effect only at the time it is called. So this demo might be help  https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect, it constrains the nodes in a box area during the layout iterations

**Comment by ketys-from-meiro** [comment]
Hm, thanks for the example. Isn't it possible to call `fitView` after iterations finishes?

**Comment by Yanyan-Wang** [comment]
> Hm, thanks for the example. Isn't it possible to call `fitView` after iterations finishes?

of course. But it might lead ti a sudden change after layout
```
graph.on('afterlayout',  e=> { 
  graph.fitView()
})

```

**Comment by sscarduzio** [comment]
It would be useful if the G6 library would offer a way to specify a constrainBox. That onTick function is easy to get wrong!
