### ISSUE TITLE
Node labels leave a trace while moving

### ISSUE THREAD

**Issue by kozhuhds** [antvis/G6#2820]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-sound-cynij?file=/src/index.js)

### Steps to reproduce
Just move graph outside the canvas partially and revert it back. Node label leaves a trace. [https://take.ms/1fPFd](https://take.ms/Gl6ab)
Screencast: [https://take.ms/Gl6ab](https://take.ms/Gl6ab)

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | macos 11.2.3 |
| Browser | chrome Version 89.0.4389.128 (Official Build) (x86_64) |

**Comment by Yanyan-Wang** [comment]
We are trying to fix the issue. Since the bbox of the text is related to lots of variables e.g. fontFamily, fontSize, fontWeight…, and also related to those variables pf the ancestor containers and browsers, the problem might be complicated and we still need some time.

For now, you could change the fontFamily of the node labels in your project to solve it temporally. For example, configure it on the graph instance:
```
  defaultNode: {
    labelCfg: {
      style: {
        fontFamily: 'Arial' // or other fontFamily
      }
    }
  }
```

**Comment by kozhuhds** [comment]
@Yanyan-Wang  hi! I appreciate your answer! just FYI: temp solution you suggested doesn't work if graph is zoomed a bit

**Comment by Yanyan-Wang** [comment]
Maybe just disable the localRefresh...

graph.get('canvas').set('localRefresh', false)

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/2492
