### ISSUE TITLE
Expose GraphTree layouts with G6.Layout

### ISSUE THREAD

**Issue by ezzaouia** [antvis/G6#2831]
We can use G6.Graph layouts using G6.Layout, but we can not do so for GraphTree-related layouts.

```
// _g2.default.Layout.mindmap is not a constructor

const subl = new G6.Layout['mindmap']({ 
    //
})
```

https://codesandbox.io/s/infallible-kalam-hwne9?file=/index.js:1696-1751

Can we use G6.Layout interface for all G6 layouts?

**Comment by Yanyan-Wang** [comment]
For now, the tree graph layouts are not expose as the API of graph layouts, instead of that, you could use it by:

import Hierarchy from '@antv/hierarchy';
const layoutData = Hierarchy['dendrogram'](treeGraphData, layoutConfig);

Note that the `treeGraphData` here is the hierarchy tree data which is different from data for graph layouts.

It seems that there are several similar requirements for tree graph layout from users, we will consider to unify them in the future

Related to https://github.com/antvis/G6/issues/2839

**Comment by Yanyan-Wang** [comment]
Supported by 4.3.0. You could use the hierarchy layouts by 

const layout = new TreeLayout({type: 'dendrogram'})
layout.layout(data)
