### ISSUE TITLE
svg 渲染所有内置箭头样式问题

### ISSUE THREAD

**Issue by L924553229** [antvis/G6#2859]
https://antv-g6.gitee.io/zh/examples/item/arrows#built-in-arrows
增加属性 renderer: 'svg', 可以复现所述问题, 谢谢

**Comment by Yanyan-Wang** [comment]
目前 svg 的箭头坐标与 canvas 相反，和这里 3.4 版本以前的坐标方向一样：https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge/#5-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4

**Comment by yflabc** [comment]
我也遇到 坐标问题可以自定义解决，但是fill填充箭头颜色是无效的，有人解决了吗

**Comment by lianghx-319** [comment]
> 我也遇到 坐标问题可以自定义解决，但是fill填充箭头颜色是无效的，有人解决了吗

箭头没有 fill color

![image](https://user-images.githubusercontent.com/27187946/131473798-db1ef4e2-a35b-4e21-91dd-1cc5d9b5cd2d.png)
![image](https://user-images.githubusercontent.com/27187946/131473820-1cac66b1-5ccc-4079-bb30-4c5deea2a41b.png)

**Comment by huangchen1031** [comment]
> > 我也遇到 坐标问题可以自定义解决，但是fill填充箭头颜色是无效的，有人解决了吗
> 
> 箭头没有 fill color
> 
> ![image](https://user-images.githubusercontent.com/27187946/131473798-db1ef4e2-a35b-4e21-91dd-1cc5d9b5cd2d.png) ![image](https://user-images.githubusercontent.com/27187946/131473820-1cac66b1-5ccc-4079-bb30-4c5deea2a41b.png)

直接在endArrow平级配置edge的fill就可以了

**Comment by yflabc** [comment]
你好，邮件已收到。

**Comment by Yanyan-Wang** [comment]
非常抱歉，当前版本(3.x、4.x)依赖的底层渲染引擎暂时不会考虑 SVG 问题的修复，渲染引擎目前正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug

Dear user, sorry to say that we may not fix the problems in SVG renderer in current versions (G6 3.x - 4.x) since it is caused by the old rendering engine which we unable to maintain any more. The rendering engine is being upgraded right now, the problems about SVG will be solved by new version in few months. And G6 will be upgraded to 5.x with new rendering engine next year.

**Comment by yflabc** [comment]
你好，邮件已收到。
