### ISSUE TITLE
引用G6报错  dependencies were not found：gl-matrix/vec2 gl-matrix/vec3

### ISSUE THREAD

**Issue by jayrenkang** [antvis/G6#3236]
import G6 from '@antv/g6';

报错信息：
**These dependencies were not found:
* gl-matrix/vec2 in ./node_modules/@antv/g-math/esm/line.js
 * gl-matrix/vec3 in ./node_modules/@antv/g-canvas/esm/util/path.js**
尝试npm install  gl-matrix/vec2 gl-matrix/vec3 时npm报错，是不是这两个包没有了啊

**Comment by jayrenkang** [comment]
G6版本4.3.8

**Comment by Blakko** [comment]
I got it to work by:
- removing ` && npm run build:mobile` here https://github.com/antvis/G6/blob/master/package.json#L19 as the mobile account isn't there
- removing `"eslint-plugin-import": "^2.22.1",` here https://github.com/antvis/G6/blob/master/package.json#L56 because it was duplicate din the devDependencies
- forced `"gl-matrix": "3.0.0",` above this line to get rid of the error you're facing https://github.com/antvis/G6/blob/master/package.json#L79

**Comment by IdreesSamadi** [comment]
I have a similar issue with G6@4.3.11 in React, any solution?

**Comment by monolithed** [comment]
https://github.com/toji/gl-matrix/issues/439

**Comment by Blakko** [comment]
After manually installing `gl-matrix` v3.4.3 (via an npm install `gl-matrix@3.4.3`) the build works again.
jest tests (`npm run test`) are still not working due to issues with the gl-matrix dependency:
```bash
Details:

        G6\node_modules\gl-matrix\dist\esm\index.js:1
        ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as glMatrix from "./common.js";
                                                                                                        ^

        SyntaxError: Unexpected token *
```

**Comment by BowenHero** [comment]
我也有这个问题请问解决了吗
