### ISSUE TITLE
当使用力导向图拖动时未稳定，打开边动画，会一直执行setState函数，导致卡顿

### ISSUE THREAD

**Issue by xiahongyuan** [antvis/G6#3542]
### 问题描述

当使用力导向图拖动时未稳定，打开边动画，会一直执行setState函数，导致卡顿
有不能将它稳定之后再开枪动画，这样就没有体验感

### 重现链接

 CodeSandbox

### 重现步骤

 CodeSandbox

### 预期行为

。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
。

### 屏幕截图或视频（可选）

![IMG_20220224_114924](https://user-images.githubusercontent.com/88996467/155454749-e4756bb7-62ff-4747-94d2-2b7b6f110cfc.jpg)

**Comment by Yanyan-Wang** [comment]
尽量避免两者同时进行。手动停止布局迭代可以这样：
graph.get('layoutController').layoutMethods[0].forceSimulation.stop()

**Comment by Yanyan-Wang** [comment]
尽量避免两者同时进行。手动停止布局迭代可以这样：
graph.get('layoutController').layoutMethods[0].forceSimulation.stop()

**Comment by xiahongyuan** [comment]
> 
也没有效果

**Comment by xiahongyuan** [comment]
停止不了迭代

**Comment by cliffordfajardo** [comment]
你好 @xiahongyuan，
您能否提交一个最小的“codesandbox”链接来重现您面临的挑战？

创建一个代码框链接可以显着帮助“G6”团队，让他们能够快速可视化并与您面临的挑战进行交互。

G6 维护人员在帮助维护这个很棒的开源库之外还有全职工作，因此任何帮助团队更容易查看您的错误的帮助表示赞赏。 否则，由于您通过不提供“codesanbox”链接为 G6 团队引入的额外挑战，预计响应时间会变慢。

我们非常感谢您提交错误报告； 我希望你能理解我们善意的意图🙏🙂

------
### English translation:
Hi,

Would you be able to submit a minimal "codesandbox" link to reproduce the challenge you are facing?
Creating a codesandbox link significantly helps the "G6" team by you enabling them to quickly visualize and interact with the challenge you are facing.

G6 maintainers have full time jobs outside of helping maintain this awesome open source library, so any help to make it easier for the team to look at your bug is appreciated. Otherwise, expect slower response times due to the additional challenge you are introducing for the G6 team by not providing a "codesandbox" link.

We really do appreciate your submitting a bug report; I hope you understand our well meaning intentions 🙏🙂
