### ISSUE TITLE
comboCombined布局下，combo过多发生了combo重叠

### ISSUE THREAD

**Issue by person001** [antvis/G6#3841]
### 问题描述

G6版本4.6.6. 内网环境使用comboCombined布局，但是节点比较多，combo也比较多。绘图出来的结果是combo存在重叠

### 重现链接

无

### 重现步骤

绘图结束

### 预期行为

希望能有配置项避免combo重叠

### 平台

- 操作系统: [Windows,]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.6 ]

### 屏幕截图或视频（可选）

![微信图片_20220805155015](https://user-images.githubusercontent.com/34431484/183030469-f5e15e19-49e3-4210-8dd7-e1f37e827239.jpg)

### 补充说明（可选）

希望得到回复

**Comment by cliffordfajardo** [comment]
Hey @person001,
Is it possible for you to share a codesandbox link reproducing the issue with fake data?
That way the G6 team can more easily play around with the behavior, otherwise the G6 team has to try and replicate your issue from scratch which is time consuming & reduces the likelihood of a bug fix or lowering the time to fix

Also, I really like your combo layout and design! ✨ 🙌 
Are you on the G6 forums or on Dingtalk to talk about G6 combos in your free time? I'm making use of Combos for the same use case you are (intranet / computer infrastructure visualization)

**Comment by person001** [comment]
我尝试在外网构建一下，因为是自定义的东西比较多。而且node和combo比较多，且点和边的关联比较少。布局很分散！

**Comment by Yanyan-Wang** [comment]
请给出在线复现 demo

**Comment by TonyLuo** [comment]
> 请给出在线复现 demo

I have the same issue about combo overlap
https://codesandbox.io/s/withered-grass-8flyf1?file=/index.js

**Comment by person001** [comment]
![image](https://user-images.githubusercontent.com/34431484/185734832-313d4e18-dc27-4b38-b4ee-c961d0a87a13.png)

**Comment by person001** [comment]
这是我在外网复刻的一个demo，数据真实，区别只有自定义的节点等
https://codesandbox.io/s/floral-fast-mceznk?file=/index.js

**Comment by person001** [comment]
@Yanyan-Wang @cliffordfajardo @TonyLuo 希望得到各位的回复，拜谢！

**Comment by person001** [comment]
如果我在外层outterLayout使用的grid布局，虽然重叠会少一些，但是存在edges的nodes 或者combos之间位置距离很远，导致边很长，也不符合实际场景，自己解决遇到了瓶颈。

**Comment by IdioticMadman** [comment]
+1

**Comment by zhang354455288** [comment]
+1

**Comment by zhang354455288** [comment]
+1

**Comment by Yanyan-Wang** [comment]
> > 请给出在线复现 demo
> 
> I have the same issue about combo overlap https://codesandbox.io/s/withered-grass-8flyf1?file=/index.js

You used comboCombined layout with G6 v4.6.0-beta.3, but it is supported after v4.6.10. Upgrade to the latest version, and the graph will be layout as expected.

**Comment by Yanyan-Wang** [comment]
> 这是我在外网复刻的一个demo，数据真实，区别只有自定义的节点等 https://codesandbox.io/s/floral-fast-mceznk?file=/index.js

默认的 outerLayout 参数为了图足够紧凑，参数可能比较保守。调整 outerLayout 的参数可以解决，factor 大一些，图会离散一些

outerLayout: new G6.Layout['force2']({
      factor: 5 // 默认是 2
    })
