### ISSUE TITLE
arrowhead position is modified by changing lineWidth on selection, but not updated until the node is moved

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#4015]
### Describe the bug

When selection is enabled on a node, the position of any edge arrowheads at that node is updated. But the effect is delayed until the node is moved.

See this gif:

![Oct-26-2022 16-51-38](https://user-images.githubusercontent.com/29077863/198074932-63dde4d2-9a01-454d-8e67-dba6cb3d423a.gif)

### Your Example Website or App

https://codesandbox.io/s/inspiring-ace-4wiz0q?file=/index.js

### Steps to Reproduce the Bug or Issue

As seen in the gif:

1. I select the node: the arrowhead does not move
2. I drag the node:  now the arrowhead moves away from the node
3. I unselect the node - the arrowhead does not move
4. I drag the node again: now the arrowhead moves back towards the node

### Expected behavior

1. I select the node: the arrowhead moves away from the node
2. I drag the node:  now the arrowhead does not move
3. I unselect the node - the arrowhead moves back towards the node
4. I drag the node again: now the arrowhead does not move

Alternatively, if the arrowhead never moved when a node was selected/unselected, I would be happy with that too.

### Platform

- OS: macOS
- Browser: chrome
- Version: chrome 106.0.5249.119 (Official Build) (arm64)

**Comment by Yanyan-Wang** [comment]
fixed by 4.7.12, the reason is G6 did not refresh the related edges when set state for a node.
for better performance on large dataset, I add a configure named `optimizeThreshold` for graph instance,  whose default value is `1000`. When the number of the graph's nodes is larger than `optimizeThreshold`,  this refreshing will be disabled. And for further consideration, `optimizeThreshold` will take effect on more situations to simplify the calculation and rendering on large dataset.
