### ISSUE TITLE
updating donuts interferes with drag

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#4091]
### Describe the bug

If donuts are added or updated on a node while the node is being dragged, the drag is ended. 

### Your Example Website or App

https://stackblitz.com/edit/react-spflig?file=index.js

### Steps to Reproduce the Bug or Issue

1. start dragging the node
2. when the setInterval updates the donuts, the drag ends

### Expected behavior

When using updateItem, the drag should continue, and the donut appearance should be correctly updated.

### Screenshots or Videos

![drag](https://user-images.githubusercontent.com/29077863/203748037-04a83616-55cb-46ef-8f4d-a1f2ace86ed4.gif)

### Platform

- OS: macOS
- Browser: Chrome 107.0.5304.110 (Official Build) (arm64) 
- G6 Version: 4.7.14

**Comment by Yanyan-Wang** [comment]
It is due to the donut node does not have update function in its definition. When it is updated, the shapes will be destroyed and re-initiated by draw function. So the target of the drag event is not the original object.

I am trying to implement the update function for donut recently. And the problem will be addressed.
