### ISSUE TITLE
To get REAL center in graph.zoom you need to use window.innerWidth and window.innerHeight NOT graph.getViewPortCenterPoint()

### ISSUE THREAD

**Issue by Radomir-Drukh** [antvis/G6#5091]
### Describe the bug

To get REAL center in graph.zoom you need to use window.innerWidth and window.innerHeight NOT graph.getViewPortCenterPoint()

graph.zoom(1.2, graph.getViewPortCenterPoint()) - WRONG

This call will zoom with move with offset

graph.zoom(1.2, {x: window.innerWidth / 2, y: window.innerHeight / 2} ) - CORRECT

This call will zoom right at the center.

Please state this fact in the documentation

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

1) Create graph that takes up only part of the screen
2) Call graph.zoom(1.2, graph.getViewPortCenterPoint())

### Expected behavior

As a user, I expected that graph.zoom(1.2, graph.getViewPortCenterPoint()) will zoom at the center of the camera view but i am seeing strange offset

### Platform

- OS: macOS
- Browser: Chrome

**Comment by Yanyan-Wang** [comment]
The implementation of getViewPortCenterPoint is:

<img width="510" alt="image" src="https://github.com/antvis/G6/assets/29593318/222c1c1a-9bb8-481e-a580-b196587aa659">

Which means the API returns the point in rendering coordinate system for the center of canvas DOM. If the graph has initial zoom (1) and not translation, the point of rendering coordinate system is equal to the center point of canvas DOM in number. But after zooming and translating (maybe caused by fitView, fitCenter, mouse wheel, etc.), they are different. Refer to the doc:  https://g6.antv.antgroup.com/en/manual/advanced/coordinate-system , where the rendering coordinate system I mentioned before is the pointX/pointY coordinate system in the doc.
